### ISSUE TITLE
Prefix Causes Verbose Feedback Issue

### ISSUE THREAD

**Issue by PhantomCaptain** [AlexProgrammerDE/PistonChat#162]
All commands that use the `sendLanguageMessage` do not respond with the messages in language.yml when running the associated commands. Changing it to `sendLanguageMessageNoPrefix` and rebuilding the plugin fixes the issue, bypassing the prefix and printing the configured feedback when running the commands.

**Comment by AlexProgrammerDE** [comment]
Can you share your config.yml and language.yml?

**Comment by PhantomCaptain** [comment]
We have used TEST now but it was empty and still not working.

```yml
# To use these prefixes you need additionally the pistonchat.<COLORCODE>
# / indicates disabled!
# This config is configured to be what 2b2t.org has.
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html
# pistonchat.prefix.green and pistonchat.chatformat.default are given by default.
whisper:
  from: '<light_purple><player_name> whispers: <message>'
  to: '<light_purple>You whisper to <player_name>: <message>'
hover-text: <gold>Message <dark_aqua><player_name>

mysql:
  host: REDACTED
  port: REDACTED
  database: REDACTED
  username: REDACTED
  password: REDACTED

strip-name-color: true
chat-formats:
  special: <gold><<player_name>>
  default: <<player_name>>

message-format: <format> <message>

console-name: '[server]'

allow-pm-self: true
allow-pm-ignored: false
only-hide-pms: true

ignore-list-size: 9
prefixes:
  green:
    prefix: '>'
    color: GREEN
```


```yml
# You can find pre translated languages on crowdin:
# https://crowdin.com/project/pistonchat
# The prefix can also be set to just "&6"
format: TEST
help-header: TEST
playeronly: You need to be a player to do this.
notonline: This player is not online!
nooneignored: No players ignored!
chaton: Chat messages now shown.
chatoff: Chat messages now hidden.
pmson: Private messages unhidden.
pmsoff: Private messages hidden.
pmself: Please do not private message yourself.
chatisoff: You have toggled off chat.
source-ignored: This person ignores you!
target-ignored: You ignore this person!
page-not-exists: This page doesn't exist.
not-a-number: Not a number!
whispering-disabled: This person has whispering disabled!
ignore: <gold>Now ignoring <yellow><player_name>
unignore: <gold>No longer ignoring <yellow><player_name>
ignorehard: <gold>Permanently ignoring <player_name>. Saved to <yellow>/ignorelist</yellow>.
unignorehard: <gold>No longer permanently ignoring <yellow><player_name>
ignorelistcleared: <gold>Ignore list cleared.
```
